---
- name: Download k3s binary x64
  get_url:
    url: https://github.com/k3s-io/k3s/releases/download/{{ k3s_version }}/k3s
    dest: /tmp/k3s
  delegate_to: localhost
  run_once: true
  become: no   
  
- name: Copy k3s binary to node
  copy:
    src: /tmp/k3s
    dest: /usr/local/bin/k3s
    mode: '0755'
